//
//  SessionInfoView.swift
//  Rayon
//
//  Created by Lakr Aream on 2022/2/11.
//

import SwiftUI

struct SessionInfoView: View {
    @EnvironmentObject var context: RDSessionAssoicatedContext

    @StateObject
    var windowObserver: WindowObserver = .init()

    let timer = Timer
        .publish(every: 1, on: .main, in: .common)
        .autoconnect()
    let lock = NSLock()

    @StateObject var info = ServerStatus()
    @State var requestThrottle: Int = 5

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 10) {
                Group {
                    ServerStatusViews.SystemInfo()
                    Divider()
                    ServerStatusViews.ProcessorInfoSummaryView()
                    Divider()
                    ServerStatusViews.MemoryInfoView()
                    Divider()
                }
                Group {
                    ServerStatusViews.FileSystemView()
                    Divider()
                    ServerStatusViews.NetworkView()
                    Divider()
                }
                Text("Generated by Rayon, updated in real-time.")
                    .font(.system(.footnote, design: .rounded))
            }
            .textSelection(.enabled)
            .environmentObject(info)
            .font(.system(.body, design: .monospaced))
            .padding(20)
        }
        .animation(.interactiveSpring(), value: info)
        .onReceive(timer) { _ in
            timerReceiver()
        }
        .background(
            HostingWindowFinder { [weak windowObserver] window in
                windowObserver?.window = window
                setWindowTitle()
            }
        )
        .onAppear {
            setWindowTitle()
        }
        .onDisappear {
            clearWindowTitle()
        }
    }

    func setWindowTitle() {
        windowObserver.window?.title = "Machine Info"
        windowObserver.window?.subtitle = "\(context.remoteIdentity.username)@\(context.remoteMachine.remoteAddress)"
    }

    func clearWindowTitle() {
        windowObserver.window?.title = ""
        windowObserver.window?.subtitle = ""
    }

    func timerReceiver() {
        guard lock.try() else {
            // operation in progress
            return
        }
        let sleepInterval = requestThrottle
        DispatchQueue.global().async {
            gathreingData(sleepInterval: sleepInterval)
            lock.unlock()
        }
    }

    func gathreingData(sleepInterval: Int) {
        debugPrint("gathreingData enter request")
        let begin = Date()
        info.requestInfoAndWait(with: context.shell)
        debugPrint("gathreingData leave request, used \(Date().timeIntervalSince(begin)) second")
        sleep(UInt32(exactly: sleepInterval) ?? 5)
    }
}
